id: PA60F12DA
initial_creation_type: input
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA3JT13371
  instance_id: http://purl.bdrc.io/resource/IE3JT13371
  collection_id: http://purl.bdrc.io/resource/PR0ET010
  language_id: None
  title:
    bo:
    - འདུལ་བ་མེ་ཏོག་ཕྲེང་རྒྱུད།
  alt_title:
    bo:
    - འཕགས་པ་གཞི་ཐམས་ཅད་ཡོད་པར་སྨྲ་བའི་འདུལ་བ་ཚིག་ལེའུར་བྱས་པ་མེ་ཏོག་གི་ཕྲེང་རྒྱུད།
  author: None
  publisher: Various
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    3244a338c3d345da990400b1d53c82cc:
      title: བམ་པོ་གཉིས་པ།
      volume_number: 1
      base_file: UT3JT13371_001_0004.txt
      reference: http://purl.bdrc.io/resource/VLDDABA62597AD037A
      image_group: null
      quality: null
  reproductionOf: []
created_at: '2021-12-31T08:20:25.391428'
last_modified_at: '2021-12-31T08:20:25.391435'
statistics:
  total_words: 60777
  total_non_words: 8225
quality:
  non_words_ratio: 0.14
